
spring:
  application:
    name: cine

  datasource:
    url: jdbc:postgresql://localhost:5432/cine
    username: postgres
    password: fcfran
    driver-class.name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      datasource: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

